name: ' Get & Cache Dependencies'
descriptions: 'Get the dependencies and cache them'
inputs:
  flag_caching:
    description: 'Whether to cache dependencies or not'
    required: false
    default: 'true'
runs: #Must have name "run"
  using: 'composite' #Must have name "composite"
  steps:
    - name: Cache dependencies
      if: inputs.flag_caching == 'true'
      id: cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          deps-node-modules-

    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.flag_caching != 'true'
      run: npm ci
      shell: bash #Composite action with "run" key needs to define in which shell we run the step