name: Reconvert Python Scripts to Notebooks
 
on:
  push:
    branches:
      - main
 
jobs:
  reconvert:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
 
      - name: Install nbconvert and nbformat
        run: |
          pip install nbconvert nbformat
 
      - name: Find and reconvert scripts
        run: |
          for original_notebook in $(find . -name "*.original.ipynb"); do
            notebook="${original_notebook%.original.ipynb}.ipynb"
            if [ ! -f "$notebook" ]; then
              echo "Restoring notebook from $original_notebook"
              cp "$original_notebook" "$notebook"
            fi
          done
 
      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code || echo "changes"
 
      - name: Commit changes
        if: steps.changes.outputs.changes == 'changes'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add **/*.ipynb
          git commit -m 'Reconvert Python scripts to Jupyter notebooks'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}