name: Convert Notebooks to Python Scripts
 
on:
  push:
    paths:
      - '**/*.ipynb'
  pull_request:
    paths:
      - '**/*.ipynb'
 
jobs:
  convert:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
 
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
 
      - name: Install nbconvert and IPython
        run: pip install nbconvert ipython
 
      - name: Find and convert notebooks
        run: |
          for notebook in $(find . -name "*.ipynb"); do
            echo "Converting $notebook to script"
            jupyter nbconvert --to script "$notebook"
            cp "$notebook" "${notebook%.ipynb}.original.ipynb"
          done

      - name: List files for debugging
        run: |
          echo "Listing files in the repo"
          ls -R 
 
      - name: Check for changes
        id: changes
        run: |
          git diff --exit-code || echo "changes"
          echo "::set-output name=changes::$(git diff --exit-code || echo 'changes')"

      - name: Debuck Check for changes output
        run: |
          echo "Changes detected: {{ steps.changes.outputs.changes }}""
 
      - name: Commit changes
        if: steps.changes.outputs.changes == 'changes'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add **/*.py **/*.original.ipynb
          git commit -m 'Convert notebooks to Python scripts and store original notebooks'
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}